name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    name: Building on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15]

    steps:
    - uses: actions/checkout@v2
    - name: install requirements
      run: brew install ccache ninja boost

    - name: Get Time
      id: time
      uses: nanzm/get-time-action@v1.0
      with:
        timeZone: 8
        format: 'YYYY-MM-DD-HH-mm-ss'

    - name: ccache cache files
      uses: actions/cache@v2
      with:
        path: .ccache
        key: ${{ matrix.os }}-ccache-${{ steps.time.outputs.time }}
        restore-keys: |
          ${{ matrix.os }}-ccache-
    
    - name: Build
      env:
        CCACHE_COMPRESS: true
        CCACHE_COMPRESSLEVEL: 6
        CCACHE_MAXSIZE: "1G"
      run: 
        export CCACHE_BASEDIR=$GITHUB_WORKSPACE
        && export CCACHE_DIR=$GITHUB_WORKSPACE/.ccache
        && ccache -z
        && cmake 
            -GNinja
            -DCMAKE_C_COMPILER_LAUNCHER=ccache
            -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
            -DCMAKE_BUILD_TYPE=Release
            -DAPPLICATION_MODELER=OFF
            -DSOFAGUI_BUILD=OFF
            -DSOFAGUI_QT=OFF
            -DSOFA_NO_OPENGL=ON
            -DSOFA_BUILD_SCENECREATOR=OFF
            -DSOFA_BUILD_TESTS=ON
            -DSOFAGUI_BUILD_TESTS=OFF
            -DSOFA_FLOATING_POINT_TYPE=double
            -DSOFA_WITH_DEPRECATED_COMPONENTS=OFF
            .
        && ninja 
        && ninja install
        && ccache -s
    - name: Archive production
      uses: actions/upload-artifact@v2
      with:
        name: sofa-slim-${{ matrix.os }}
        path: install
